services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    command: uvicorn api.main:app --host 0.0.0.0 --port 8001 --reload
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      PROJECT_API: ${PROJECT_API}

      # Database Configuration
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_DATABASE: ${DB_DATABASE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}

      # Docker Image Configuration
      IMAGE_NAME: ${IMAGE_NAME}
      IMAGE_TAG: ${IMAGE_TAG}

      # Jinja Configuration
      PROMPT_TEMPLATES_FOLDER: ${PROMPT_TEMPLATES_FOLDER}

      # API Keys
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      AGNO_API_KEY: ${AGNO_API_KEY}

      AGNO_MONITOR: "True"
      WAIT_FOR_DB: "True"
      PRINT_ENV_ON_LOAD: "True"
      PYTHONPATH: "src"

      # Wati Templates
      WALLETY_API_URL: "https://staging.api.wallety.cash/api/v1"
      MESSAGING_API_URL: "https://api.messaging.wallety.cash/api/v1"
      MESSAGE_LOG_TYPE_ID: "76496eb7-bb57-4aef-9f92-6a6bf5a07a37"

      # Ollama Configuration
      OLLAMA_HOME: "$HOME/.ollama"

    networks:
      - agno-agent-api
      - nginxproxymanager_default
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  nginxproxymanager_default:
    external: true
  agno-agent-api:

volumes:
  pgdata:
